# Generated by Django 2.0.2 on 2018-03-06 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_auto_20180301_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients_Coktails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.Cocktail')),
                ('i_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.Ingredients')),
            ],
        ),
    ]
