# Generated by Django 2.0.2 on 2018-03-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_auto_20180306_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient_coktail',
            name='c_name',
        ),
        migrations.RemoveField(
            model_name='ingredient_coktail',
            name='i_name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cocktails',
            field=models.ManyToManyField(to='cocktails.Cocktail'),
        ),
        migrations.DeleteModel(
            name='Ingredient_Coktail',
        ),
    ]
