# Generated by Django 2.0.2 on 2018-03-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_auto_20180306_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
