# Generated by Django 2.0.2 on 2018-03-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_ingredient_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='is_favorite',
            new_name='is_alcohol',
        ),
    ]
